Globalize.addCultureInfo("de", {
	messages : {
		"settings" : "Einstellungen",
		"infos" : "Informationen",
		"feedback" : "Feedback",
		"receipts" : "Belege",
		"receipt" : "Beleg",
		"newReceipt" : "Neuer Beleg",
		"about" : "Infos",
		"name" : "Bezeichnung",
		"amount" : "Betrag",
		"currency" : "Währung",
		"date" : "Datum",
		"receiptKind" : "Belegart",
		"kindOfPayment" : "Zahlungsart",
		"delete" : "Löschen",
		"send" : "Senden",
		"deleteThisReceipt" : "Diesen Beleg löschen",
		"nameIsRequired" : "Bezeichung nicht angegeben",
		"amountIsRequired" : "Betrag nicht angegeben",
		"dateIsRequired" : "Datum nicht angegeben",
		"receiptKindIsRequired" : "Belegart nicht angegeben",
		"kindOfPaymentIsRequired" : "Zahlungsart nicht angegeben",
		"currencyIsRequired" : "Währung nicht angegeben",
		"validationErrorMessage" : "Folgende Eingaben fehlen oder sind fehlerhaft:",
		"saveButton" : "Speichern",
		"copyReceipt" : "Beleg Kopieren",
		"copyReceiptConfirmQuestion" : "Beleg kopieren?",
		"copyReceiptConfirmText" : "Der Beleg wird gespeichert und kopiert.<br> Soll dieser Vorgang durchgeführt werden?",
		"copyReceiptErrorMessage" : "<br>Der Beleg wurde nicht kopiert.",
		"infosText" : "Anlegen, Ändern und Löschen von Belegen online oder offline.Synchronisierung mit Sammelbelegen (Menü Mitarbeiter/Reisekosten/Sammelbelege) mit Push & Sync. Anmeldung mit Firmenkennung, Benutzerkennung und Mobiles Passwort (Menü Mitarbeiter/Stammdaten/Mobile). Support/Feedback: per E-Mail an mobile.support@hrworks.de",
		"infosHeading": "Wichtige Informationen",
		"companyid": "Firmenkennung",
		"userid" : "Benutzerkennung",
		"mobilePassword" : "Mobiles Passwort",
		"settingsText" : "Verwenden Sie die Firmen-& Benutzerkennung, mit der Sie sich unter www.hrworks.de anmelden. Das mobile Passwort finden Sie in HRworks im Menü Mitarbeiter/Stammdaten/Mobile.",
		"server" : "Server",
		"feedbackText" : "Was möchten Sie uns mitteilen?",
		"Key_AppTitle" : "HRworks - Belege"
	}
});
