Globalize.addCultureInfo("default", {
	messages : {
		"settings" : "Settings",
		"infos" : "Informations",
		"feedback" : "Feedback",
		"receipts" : "Receipts",
		"receipt" : "Receipt",
		"newReceipt" : "New Receipt",
		"about" : "About",
		"name" : "Receipt name",
		"amount" : "Amount",
		"currency" : "Currency",
		"date" : "Date",
		"receiptKind" : "Receipt Kind",
		"kindOfPayment" : "Kind of Payment",
		"delete" : "Delete",
		"deleteReceipt" : "Delete receipt",
		"send" : "Send",
		"deleteThisReceipt" : "Delete this Receipt",
		"nameIsRequired" : "Receiptname is required",
		"amountIsRequired" : "Amount is required",
		"dateIsRequired" : "Date is required",
		"receiptKindIsRequired" : "Receipt Kind is required",
		"kindOfPaymentIsRequired" : "Kind of Payment is required",
		"currencyIsRequired" : "Currency is required",
		"validationErrorMessage" : "The following entries are missing or incorrect:",
		"saveButton" : "Save",
		"copyReceipt" : "Copy Receipt",
		"copyReceiptConfirmQuestion" : "Copy Receipt?",
		"copyReceiptConfirmText" : "The present receipt will be saved and copyed.<br> Are you sure?",
		"copyReceiptErrorMessage" : "<br>The receipt was not copied.",
		"infosText" : "Dummytext",
		"infosHeading": "Informations",
		"companyid": "Companyid",
		"userid" : "Userid",
		"mobilePassword" : "Mobile Password",
		"settingsText" : "Dummy Text",
		"server" : "Server",
		"feedbackText" : "Was möchten Sie uns mitteilen?",
		"Key_AppTitle" : "HRworks Receipts"
	}
});
